CREATE DATABASE nossa_agua default character set utf8;

USE nossa_agua;
CREATE TABLE tabela_de_usuarios
(CPF VARCHAR(15) NOT NULL,
NOME VARCHAR(100) NOT NULL,
E_MAIL VARCHAR(100) NOT NULL,
N_CELULAR VARCHAR(15) NOT NULL,
CEP VARCHAR(15) NOT NULL,
RUA VARCHAR(100) NOT NULL,
NUMERO INT default 'Não Possui',
BAIRRO VARCHAR(100) NOT NULL,
PRIMARY KEY (CPF));	

CREATE TABLE tabela_de_registros
(DATA_REGISTRO TIMESTAMP default current_timestamp(),
DATA_ANALISE DATE,
CPF VARCHAR(15) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
FALTOU_AGUA VARCHAR(100) NULL,
QUALIDADE_DA_AGUA VARCHAR(100) NULL,
PERIODO INT,
PRIMARY KEY (CPF));


ALTER TABLE tabela_de_registros ADD CONSTRAINT FK_Usuarios
FOREIGN KEY (BAIRRO) REFERENCES tabela_de_usuarios (BAIRRO);

